# https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
# http://jekyllrb.com/docs/configuration/
baseurl: /
encoding: utf-8
lsi: false
pygments: true
safe: true
timezone: America/Chicago
exclude: [ node_modules, src ]