- name-base: services_01
  xs-width: 480
  sm-width: 768
  md-width: 909
  lg-width: 909
  description: Services 1
  optimal-width: 909
  optimal-height: 781
  extension: jpg
- name-base: services_02
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Services 2
  optimal-width: 1200
  optimal-height: 907
  extension: jpg
- name-base: services_03
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Services 3
  optimal-width: 1200
  optimal-height: 726
  extension: jpg
- name-base: services_04
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Services 4
  optimal-width: 1200
  optimal-height: 477
  extension: jpg
- name-base: services_05
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Services 5
  optimal-width: 1200
  optimal-height: 596
  extension: jpg
- name-base: services_06
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Services 6
  optimal-width: 1200
  optimal-height: 869
  extension: jpg