- name-base: staging_01
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 01
  optimal-width: 1200
  optimal-height: 900
  extension: jpg
- name-base: staging_02
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 02
  optimal-width: 1200
  optimal-height: 900
  extension: jpg
- name-base: staging_03
  xs-width: 240
  sm-width: 323
  md-width: 560
  lg-width: 506
  description: Staging 03
  optimal-width: 560
  optimal-height: 747
  extension: jpg
- name-base: staging_04
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 04
  optimal-width: 1200
  optimal-height: 900
  extension: jpg
- name-base: staging_05
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 05
  optimal-width: 1200
  optimal-height: 900
  extension: jpg
- name-base: staging_07
  xs-width: 240
  sm-width: 323
  md-width: 560
  lg-width: 506
  description: Staging 07
  optimal-width: 560
  optimal-height: 747
  extension: jpg
- name-base: staging_08
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 08
  optimal-width: 1200
  optimal-height: 900
  extension: jpg
- name-base: staging_09
  xs-width: 240
  sm-width: 323
  md-width: 560
  lg-width: 506
  description: Staging 09
  optimal-width: 560
  optimal-height: 747
  extension: jpg
- name-base: staging_10
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 10
  optimal-width: 1200
  optimal-height: 900
  extension: jpg
- name-base: staging_32
  xs-width: 480
  sm-width: 768
  md-width: 992
  lg-width: 1200
  description: Staging 32
  optimal-width: 2400
  optimal-height: 1600
  extension: jpg
